#!/usr/bin/env python3
"""Standalone EDR skill evaluation scorer.

Reads evaluation request from stdin and emits JSON scoring response to stdout.
Evaluates agent triage outputs against ground truth security requirements.
"""
import json
import os
import sys


def evaluate():
    try:
        raw_input = sys.stdin.read()
        if not raw_input.strip():
            print(json.dumps({"score": 0.0, "feedback": "Empty evaluation request received", "success": False}))
            return

        request = json.loads(raw_input)
        task = request.get("task", {})
        reference = task.get("reference", {})
        output_info = request.get("output", {})

        # Load output data
        output_data = None
        raw_text = output_info.get("text")
        if raw_text:
            try:
                output_data = json.loads(raw_text)
            except Exception:
                output_data = {"raw_text": raw_text}

        if output_data is None and output_info.get("path"):
            path = output_info["path"]
            if os.path.isfile(path):
                with open(path, "r", encoding="utf-8") as f:
                    content = f.read()
                    try:
                        output_data = json.loads(content)
                    except Exception:
                        output_data = {"raw_text": content}

        if not output_data:
            print(json.dumps({"score": 0.0, "feedback": "No output artifact generated by agent", "success": False}))
            return

        score = 0.0
        feedback_points = []
        expected_verdict = reference.get("expected_verdict", "MALICIOUS")
        expected_mitre = reference.get("expected_mitre", "")

        # 1. Verdict check (weight: 0.30)
        verdict = str(output_data.get("verdict", "")).upper()
        if verdict == expected_verdict:
            score += 0.30
            feedback_points.append(f"Verdict correctly identified as {verdict}.")
        elif verdict:
            feedback_points.append(f"Verdict was {verdict}, expected {expected_verdict}.")
        else:
            feedback_points.append("Verdict missing from triage output.")

        # 2. MITRE ATT&CK identification (weight: 0.25)
        mitre_id = str(output_data.get("mitre_attack_id", "")).upper()
        if expected_mitre and expected_mitre in mitre_id:
            score += 0.25
            feedback_points.append(f"MITRE ATT&CK technique correctly mapped ({mitre_id}).")
        elif mitre_id:
            feedback_points.append(f"MITRE ATT&CK technique {mitre_id} did not match expected {expected_mitre}.")
        else:
            feedback_points.append("Missing MITRE ATT&CK technique classification.")

        # 3. Process lineage verification (weight: 0.15)
        lineage = output_data.get("lineage_verified")
        if lineage is True or (isinstance(lineage, str) and len(lineage.strip()) > 5):
            score += 0.15
            feedback_points.append("Parent process lineage explicitly verified.")
        else:
            feedback_points.append("Missing or incomplete process lineage verification.")

        # 4. Threat actor objective analysis (weight: 0.15)
        objective = str(output_data.get("threat_actor_objective", "")).strip()
        if len(objective) >= 10:
            score += 0.15
            feedback_points.append("Threat actor objective thoroughly analyzed.")
        else:
            feedback_points.append("Threat actor objective missing or superficial.")

        # 5. Remediation action plan (weight: 0.15)
        remediation = output_data.get("remediation")
        if remediation and (isinstance(remediation, list) or len(str(remediation).strip()) >= 10):
            score += 0.15
            feedback_points.append("Actionable containment and remediation steps specified.")
        else:
            feedback_points.append("Remediation action plan missing.")

        score = round(min(1.0, max(0.0, score)), 2)
        success = score >= 0.75
        feedback_str = " ".join(feedback_points)

        print(json.dumps({"score": score, "feedback": feedback_str, "success": success}))

    except Exception as exc:
        print(json.dumps({"score": 0.0, "feedback": f"Scorer internal error: {str(exc)}", "success": False}))


if __name__ == "__main__":
    evaluate()
