//! Ghost Trap Canary System for OpenỌ̀ṣọ́ọ̀sì.
//!
//! Automatically deploys and monitors sensitive-looking decoy files
//! (Honey-Files) across the system. Any access to these files by
//! third-party processes triggers an immediate high-confidence alert.

use std::path::{Path, PathBuf};
use std::fs;
use tracing::{info, warn};

/// A honey-file (canary) deployed on the system.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GhostCanary {
    pub path: PathBuf,
    pub decoy_type: String,
    pub original_content_hash: String,
}

pub struct CanaryManager {
    base_dirs: Vec<PathBuf>,
}

impl CanaryManager {
    pub fn new() -> Self {
        let mut base_dirs = vec![
            std::env::temp_dir().join("osoosi-traps"),
        ];

        // Add common user folders if they exist
        #[cfg(target_os = "windows")]
        {
            if let Ok(profile) = std::env::var("USERPROFILE") {
                let p = PathBuf::from(profile);
                base_dirs.push(p.join("Documents"));
                base_dirs.push(p.join("Desktop"));
            }
        }

        #[cfg(target_os = "linux")]
        {
            if let Ok(home) = std::env::var("HOME") {
                let p = PathBuf::from(home);
                base_dirs.push(p.join("Documents"));
                base_dirs.push(p.join(".ssh"));
            }
        }

        Self { base_dirs }
    }

    /// Deploy a set of Ghost Traps across the system.
    pub fn deploy_canaries(&self) -> Vec<GhostCanary> {
        let mut deployed = Vec::new();
        let decoys = vec![
            ("passwords_2025.txt", "Credentials"),
            ("client_billing_records.xlsx", "Financials"),
            ("id_rsa_backup", "SSH Key"),
            ("aws_credentials_old.ini", "Cloud Config"),
            ("salary_list.pdf", "HR Data"),
        ];

        for dir in &self.base_dirs {
            // Ensure the directory exists; skip if we can't create it
            if !dir.exists() {
                match fs::create_dir_all(dir) {
                    Ok(_) => {},
                    Err(e) => {
                        warn!("Canary: skipping {:?} — cannot create directory: {}", dir, e);
                        continue;
                    }
                }
            }

            // Verify directory is actually writable (OneDrive junctions can look
            // like they exist but fail on write)
            let probe = dir.join(".osoosi_probe");
            match fs::write(&probe, b"probe") {
                Ok(_) => { let _ = fs::remove_file(&probe); }
                Err(e) => {
                    warn!("Canary: skipping {:?} — directory not writable: {}", dir, e);
                    continue;
                }
            }

            for (name, decoy_type) in &decoys {
                let path = dir.join(name);
                if !path.exists() {
                    let content = format!("-- Ghost Trap Canary --\nGenerated by OpenOdidere\nType: {}\nNode: {}\nTS: {}\n\nDO NOT MODIFY OR DELETE.", 
                        decoy_type, hostname::get().unwrap_or_default().to_string_lossy(), chrono::Utc::now());
                    
                    if let Err(e) = fs::write(&path, content) {
                        warn!("Failed to deploy canary at {:?}: {}", path, e);
                    } else {
                        info!("Ghost Trap deployed: {:?} ({})", path, decoy_type);
                        deployed.push(GhostCanary {
                            path: path.clone(),
                            decoy_type: name.to_string(),
                            original_content_hash: "seed".to_string(),
                        });
                    }
                }
            }
        }
        deployed
    }

    /// Check if a given file path is a known Ghost Trap.
    pub fn is_canary(&self, path: &Path) -> bool {
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        let decoys = [
            "passwords_2025.txt", "client_billing_records.xlsx", "id_rsa_backup",
            "aws_credentials_old.ini", "salary_list.pdf"
        ];
        decoys.contains(&name)
    }
}
