//! Decentralized Trust Model for Odídẹrẹ́.
//!
//! Includes Decentralized Identifiers (DID), Proof of Execution (PoE),
//! and Mutual Attestation structures.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A Decentralized Identifier (DID) representing an Odídẹrẹ́ node.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NodeDID {
    pub id: String,         // e.g., "did:osoosi:12D3KooWN6LE..."
    pub public_key: String, // Hex-encoded Ed25519 public key
}

impl std::fmt::Display for NodeDID {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.id)
    }
}

/// A "Proof of Execution" verifying that a piece of data is part of a node's Merkle Audit Trail.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MerkleProof {
    pub leaf_hash: String,
    pub root_hash: String,
    pub siblings: Vec<String>,
    pub index: usize,
}

/// A Trust Certificate issued after a successful Mutual Attestation (challenge-response protocol).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrustCertificate {
    pub issuer_did: NodeDID,
    pub subject_did: NodeDID,
    pub binary_hash: String, // Hash of the WASM/Runtime binary verified during attestation
    pub memory_config_hash: String,
    pub issued_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
    pub signature: String,
}

pub fn default_pcr_selection() -> Vec<u32> {
    vec![0, 7, 16]
}

/// A Challenge-Response packet for binary integrity checks and TPM 2.0 attestation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AttestationChallenge {
    pub nonce: [u8; 32],
    pub challenger_did: NodeDID,
    pub timestamp: DateTime<Utc>,
    #[serde(default = "default_pcr_selection")]
    pub pcr_selection: Vec<u32>,
}

impl AttestationChallenge {
    pub fn new(challenger_did: NodeDID, pcr_selection: Vec<u32>) -> Self {
        use rand::RngCore;
        let mut nonce = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut nonce);
        Self {
            nonce,
            challenger_did,
            timestamp: Utc::now(),
            pcr_selection: if pcr_selection.is_empty() {
                default_pcr_selection()
            } else {
                pcr_selection
            },
        }
    }
}

/// Hardware or software-anchored TPM 2.0 quote structure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TpmQuote {
    /// Composite digest of all selected PCRs: Sha256(PCR_i || PCR_j || ...)
    pub pcr_digest: String,
    /// Selected PCR indices in this quote
    pub pcr_indices: Vec<u32>,
    /// Quoted digest: Sha256(challenge_nonce || pcr_digest)
    pub quoted_digest: String,
    /// Whether this quote was generated by physical hardware TPM (true) or clean fallback (false)
    pub hardware_backed: bool,
    /// Raw TPM quote bytes if available from TBS / tpm2-tools
    #[serde(default)]
    pub raw_quote: Option<Vec<u8>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AttestationResponse {
    pub challenge_nonce: [u8; 32],
    pub binary_hash: String,
    pub config_hash: String,
    pub responder_did: NodeDID,
    pub signature: String, // Signature of (nonce + binary_hash + config_hash + pcr_digest)
    #[serde(default)]
    pub pcr_values: std::collections::BTreeMap<u32, String>,
    #[serde(default)]
    pub tpm_quote: Option<TpmQuote>,
}

/// Golden Baseline policy for attestation verification.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GoldenBaseline {
    /// Acceptable SHA256 hashes of the executable binary (PCR 0 or binary hash).
    #[serde(default)]
    pub allowed_binary_hashes: Vec<String>,
    /// Acceptable SHA256 hashes of the system/mesh config.
    #[serde(default)]
    pub allowed_config_hashes: Vec<String>,
    /// Acceptable PCR values by PCR index (e.g. PCR 0, PCR 7, PCR 16).
    #[serde(default)]
    pub expected_pcrs: std::collections::BTreeMap<u32, Vec<String>>,
    /// Whether attestation must strictly be hardware-backed (reject software fallback).
    #[serde(default)]
    pub require_hardware_tpm: bool,
    /// Maximum allowed age for challenge nonce in seconds (to prevent replay attacks).
    #[serde(default = "default_max_nonce_age_secs")]
    pub max_nonce_age_secs: u64,
}

fn default_max_nonce_age_secs() -> u64 {
    300
}

impl Default for GoldenBaseline {
    fn default() -> Self {
        Self {
            allowed_binary_hashes: Vec::new(),
            allowed_config_hashes: Vec::new(),
            expected_pcrs: std::collections::BTreeMap::new(),
            require_hardware_tpm: false,
            max_nonce_age_secs: default_max_nonce_age_secs(),
        }
    }
}

impl GoldenBaseline {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn allow_binary_hash(mut self, hash: impl Into<String>) -> Self {
        self.allowed_binary_hashes.push(hash.into());
        self
    }

    pub fn allow_config_hash(mut self, hash: impl Into<String>) -> Self {
        self.allowed_config_hashes.push(hash.into());
        self
    }

    pub fn allow_pcr(mut self, pcr: u32, hash: impl Into<String>) -> Self {
        self.expected_pcrs.entry(pcr).or_default().push(hash.into());
        self
    }

    pub fn require_hardware(mut self, require: bool) -> Self {
        self.require_hardware_tpm = require;
        self
    }
}

/// Errors occurring during mutual attestation and Golden Baseline verification.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, thiserror::Error)]
pub enum AttestationError {
    #[error("Invalid cryptographic signature")]
    InvalidSignature,
    #[error("Replay attack detected: nonce mismatch or expired challenge")]
    NonceReplayDetected,
    #[error("Corrupted binary hash: actual {actual} not in golden baseline")]
    BinaryHashMismatch { actual: String },
    #[error("Corrupted config hash: actual {actual} not in golden baseline")]
    ConfigHashMismatch { actual: String },
    #[error("PCR {pcr_index} mismatch: actual {actual} does not match golden baseline")]
    PcrMismatch { pcr_index: u32, actual: String },
    #[error("Missing requested PCR {0} in response")]
    MissingPcr(u32),
    #[error("Hardware-backed TPM quote required but software fallback received")]
    HardwareTpmRequired,
    #[error("TPM quote digest verification failed: expected {expected}, actual {actual}")]
    QuoteDigestMismatch { expected: String, actual: String },
    #[error("Invalid public key: {0}")]
    InvalidPublicKey(String),
}

/// Dynamic Reputation Score for EigenTrust-lite.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReputationScore {
    pub node_id: String,
    pub score: f32, // 0.0 to 1.0 (1.0 = absolute trust)
    pub alerts_verified: u64,
    pub false_positives: u64,
    pub last_updated: DateTime<Utc>,
}

/// A peer requesting to join the mesh, awaiting user approval.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingJoinRequest {
    pub peer_id: String,
    pub multiaddr: Option<String>,
    pub reputation_score: f32,
    pub alerts_verified: u64,
    pub false_positives: u64,
    pub discovered_at: DateTime<Utc>,
}

/// A peer that has been quarantined from the mesh due to suspicious behavior.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuarantinedPeer {
    pub peer_id: String,
    pub reason: String,
    pub reputation_score: f32,
    pub quarantined_at: DateTime<Utc>,
    pub released_at: Option<DateTime<Utc>>,
    pub active: bool,
}
